### ISSUE TITLE
ModuleNotFoundError: No module named 'vq_method.flash_attn_with_score'

### ISSUE THREAD

**Issue by TKONIY** [HugoZHL/PQCache#3]
Thanks for your brilliant work! I ran into a problem and wonder whether you could help.

I tried `run_mistral.sh` and encountered an error of `flash_attn_with_score`. For my understanding, it might be a flash_attn variant that outputs the attention scores. However, I could not find its implementation in this project. 

```python
ModuleNotFoundError: No module named 'vq_method.flash_attn_with_score'
```

**Comment by La-tale** [comment]
Thanks for the great work!

I also got the same problem as above.
It seems that "flash_attn_with_score.py" file is missing.
I'd appreciate any help you can provide!

**Comment by HugoZHL** [comment]
Thank you for your attention to our work! In the PQCache method, this particular function is not utilized, so you may safely remove the corresponding import line to prevent errors. Additionally, for your information, we are planning to release an updated version of PQCache soon, which will address and eliminate these bugs.

**Comment by La-tale** [comment]
Thank you for your quick response and update!
Looking forward to it!
