### ISSUE TITLE
VQMistralForCausalLM.forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by ShawnzzWu** [HugoZHL/PQCache#5]
Thanks for your great work!
I'm currently trying to reproduce your experiments following the instruction.
Somehow this error pumped out during model.generate. 
After adding cache_position=None to forward method, another error saying "in prepare_inputs_for_generation
    cache_length = past_length = past_key_values[0][0].shape[2]   index out of range'" occured.
So I want to ask if you guys knows how to deal with this issue?
Looking forward to your reply, thanks a lot.

**Comment by HugoZHL** [comment]
Thank you for your interest in our work! It seems you have used another version of the transformer package. We  have just updated our codebase with an `env.yml` file to specify the version of libraries. Please try building conda environment from this file or manually adjusting the version.
